name: radio_g1
description: Radio Ğ1 Liberty
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.5
  http: 1.4.0
  share_plus: 11.0.0
  in_app_review: 2.0.10
  markdown_widget: ^2.2.0
  flutter_svg: 2.1.0
  url_launcher: 6.3.1
  text_scroll: 0.2.0
  sleek_circular_slider : 2.0.1
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  volume_regulator: 2.4.1
  dart_common_utils: 1.0.0
  logging: ^1.2.0

dev_dependencies:
  flutter_lints: 5.0.0
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.4.1
  change_app_package_name: 1.3.0

flutter_icons:
  image_path: "assets/appicon/appicon.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/appicon/appicon-adaptive.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#172230"
  image: assets/splash/splash.png
  android: true
  ios: true

  android_12:
    color: "#172230"
    color_dark: "#172230"
    image: assets/splash/splash12.png
    image_dark: assets/splash/splash12.png

flutter:
  uses-material-design: true
  assets: 
    - assets/text/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Custom
      fonts:
        - asset: fonts/Light.ttf
          weight: 300
        - asset: fonts/Regular.ttf
          weight: 400
        - asset: fonts/Medium.ttf
          weight: 500
        - asset: fonts/SemiBold.ttf
          weight: 600
        - asset: fonts/Bold.ttf
          weight: 700
        - asset: fonts/ExtraBold.ttf
          weight: 800
